# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'hmi_view.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QSlider, QSpacerItem, QTabWidget,
    QTextBrowser, QVBoxLayout, QWidget)

from HMI.QtMyWidgets import QSwitchButton

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1080, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setStyleSheet(u"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1078, 718))
        self.scrollAreaWidgetContents.setMinimumSize(QSize(1078, 718))
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet(u"QTabBar::tab {\n"
"    min-height: 30px; \n"
"    min-width: 150px; \n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background-color: #9d9d9d; \n"
"    border: 1px solid #000000;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #aaffff; \n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #FFFFFF;\n"
"    border-bottom-color: #f0f0f0;\n"
"}")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tab.setAutoFillBackground(True)
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(470, 250, 591, 181))
        self.label_43 = QLabel(self.groupBox_4)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(240, 150, 171, 16))
        self.cBox_setPosSevro4 = QComboBox(self.groupBox_4)
        self.cBox_setPosSevro4.addItem("")
        self.cBox_setPosSevro4.addItem("")
        self.cBox_setPosSevro4.addItem("")
        self.cBox_setPosSevro4.addItem("")
        self.cBox_setPosSevro4.addItem("")
        self.cBox_setPosSevro4.setObjectName(u"cBox_setPosSevro4")
        self.cBox_setPosSevro4.setGeometry(QRect(450, 147, 131, 22))
        self.entry_servoDegree = QLineEdit(self.groupBox_4)
        self.entry_servoDegree.setObjectName(u"entry_servoDegree")
        self.entry_servoDegree.setGeometry(QRect(130, 80, 68, 22))
        self.btn_moveServo = QPushButton(self.groupBox_4)
        self.btn_moveServo.setObjectName(u"btn_moveServo")
        self.btn_moveServo.setGeometry(QRect(20, 123, 181, 41))
        self.label_40 = QLabel(self.groupBox_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(240, 30, 54, 16))
        self.sw_Grab = QSwitchButton(self.groupBox_4)
        self.sw_Grab.setObjectName(u"sw_Grab")
        self.sw_Grab.setGeometry(QRect(530, 27, 51, 21))
        self.sw_Grab.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.label_38 = QLabel(self.groupBox_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(20, 30, 61, 16))
        self.label_41 = QLabel(self.groupBox_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(240, 70, 71, 16))
        self.cBox_setPosSevro3 = QComboBox(self.groupBox_4)
        self.cBox_setPosSevro3.addItem("")
        self.cBox_setPosSevro3.addItem("")
        self.cBox_setPosSevro3.addItem("")
        self.cBox_setPosSevro3.addItem("")
        self.cBox_setPosSevro3.addItem("")
        self.cBox_setPosSevro3.setObjectName(u"cBox_setPosSevro3")
        self.cBox_setPosSevro3.setGeometry(QRect(450, 107, 131, 22))
        self.label_39 = QLabel(self.groupBox_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(20, 80, 54, 16))
        self.sw_tiltCam = QSwitchButton(self.groupBox_4)
        self.sw_tiltCam.setObjectName(u"sw_tiltCam")
        self.sw_tiltCam.setGeometry(QRect(530, 67, 51, 21))
        self.sw_tiltCam.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.cBox_chooseServo = QComboBox(self.groupBox_4)
        self.cBox_chooseServo.addItem("")
        self.cBox_chooseServo.addItem("")
        self.cBox_chooseServo.addItem("")
        self.cBox_chooseServo.addItem("")
        self.cBox_chooseServo.setObjectName(u"cBox_chooseServo")
        self.cBox_chooseServo.setGeometry(QRect(130, 30, 68, 22))
        self.label_42 = QLabel(self.groupBox_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(240, 110, 71, 16))
        self.line = QFrame(self.groupBox_4)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(240, 50, 341, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.groupBox_4)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(240, 90, 341, 16))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.groupBox_4)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(240, 130, 341, 16))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.groupBox_5 = QGroupBox(self.tab)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(690, 440, 371, 221))
        self.logText = QTextBrowser(self.groupBox_5)
        self.logText.setObjectName(u"logText")
        self.logText.setGeometry(QRect(10, 20, 351, 192))
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 441, 651))
        self.label_25 = QLabel(self.groupBox)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 580, 71, 16))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 180, 54, 16))
        self.entryR_j3Clk = QLineEdit(self.groupBox)
        self.entryR_j3Clk.setObjectName(u"entryR_j3Clk")
        self.entryR_j3Clk.setGeometry(QRect(70, 80, 51, 20))
        self.entryR_j3Clk.setReadOnly(True)
        self.entryR_j1Clk = QLineEdit(self.groupBox)
        self.entryR_j1Clk.setObjectName(u"entryR_j1Clk")
        self.entryR_j1Clk.setGeometry(QRect(70, 20, 51, 20))
        self.entryR_j1Clk.setReadOnly(True)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 54, 16))
        self.slider_xPos = QSlider(self.groupBox)
        self.slider_xPos.setObjectName(u"slider_xPos")
        self.slider_xPos.setGeometry(QRect(10, 240, 411, 51))
        self.slider_xPos.setMinimum(-2000)
        self.slider_xPos.setMaximum(2000)
        self.slider_xPos.setPageStep(1)
        self.slider_xPos.setOrientation(Qt.Orientation.Horizontal)
        self.slider_xPos.setInvertedAppearance(False)
        self.slider_xPos.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slider_xPos.setTickInterval(26)
        self.sw_realTime = QSwitchButton(self.groupBox)
        self.sw_realTime.setObjectName(u"sw_realTime")
        self.sw_realTime.setGeometry(QRect(370, 20, 51, 21))
        self.sw_realTime.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.slider_zPos = QSlider(self.groupBox)
        self.slider_zPos.setObjectName(u"slider_zPos")
        self.slider_zPos.setGeometry(QRect(10, 380, 411, 51))
        self.slider_zPos.setMinimum(200)
        self.slider_zPos.setMaximum(3000)
        self.slider_zPos.setPageStep(1)
        self.slider_zPos.setSliderPosition(1990)
        self.slider_zPos.setOrientation(Qt.Orientation.Horizontal)
        self.slider_zPos.setInvertedAppearance(False)
        self.slider_zPos.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slider_zPos.setTickInterval(20)
        self.slider_speedX = QSlider(self.groupBox)
        self.slider_speedX.setObjectName(u"slider_speedX")
        self.slider_speedX.setGeometry(QRect(10, 520, 411, 51))
        self.slider_speedX.setMinimum(-20000)
        self.slider_speedX.setMaximum(20000)
        self.slider_speedX.setSingleStep(10)
        self.slider_speedX.setPageStep(100)
        self.slider_speedX.setOrientation(Qt.Orientation.Horizontal)
        self.slider_speedX.setInvertedAppearance(False)
        self.slider_speedX.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slider_speedX.setTickInterval(200)
        self.entry_zPos = QLineEdit(self.groupBox)
        self.entry_zPos.setObjectName(u"entry_zPos")
        self.entry_zPos.setGeometry(QRect(200, 80, 51, 20))
        self.slider_stepSize = QSlider(self.groupBox)
        self.slider_stepSize.setObjectName(u"slider_stepSize")
        self.slider_stepSize.setGeometry(QRect(10, 450, 411, 51))
        self.slider_stepSize.setMinimum(80)
        self.slider_stepSize.setMaximum(2000)
        self.slider_stepSize.setPageStep(1)
        self.slider_stepSize.setOrientation(Qt.Orientation.Horizontal)
        self.slider_stepSize.setInvertedAppearance(False)
        self.slider_stepSize.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slider_stepSize.setTickInterval(14)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(140, 80, 54, 16))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 20, 54, 16))
        self.label_22 = QLabel(self.groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 510, 71, 16))
        self.entryR_j2Clk = QLineEdit(self.groupBox)
        self.entryR_j2Clk.setObjectName(u"entryR_j2Clk")
        self.entryR_j2Clk.setGeometry(QRect(70, 50, 51, 20))
        self.entryR_j2Clk.setReadOnly(True)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 180, 54, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 54, 16))
        self.sw_disEnJ14 = QSwitchButton(self.groupBox)
        self.sw_disEnJ14.setObjectName(u"sw_disEnJ14")
        self.sw_disEnJ14.setGeometry(QRect(370, 180, 51, 21))
        self.sw_disEnJ14.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.slider_speedY = QSlider(self.groupBox)
        self.slider_speedY.setObjectName(u"slider_speedY")
        self.slider_speedY.setGeometry(QRect(10, 590, 411, 51))
        self.slider_speedY.setMinimum(-20000)
        self.slider_speedY.setMaximum(20000)
        self.slider_speedY.setSingleStep(10)
        self.slider_speedY.setPageStep(100)
        self.slider_speedY.setOrientation(Qt.Orientation.Horizontal)
        self.slider_speedY.setInvertedAppearance(False)
        self.slider_speedY.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slider_speedY.setTickInterval(200)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 50, 54, 16))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(280, 60, 54, 16))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 50, 54, 16))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(280, 140, 71, 16))
        self.label_21 = QLabel(self.groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 440, 71, 16))
        self.sw_tracking = QSwitchButton(self.groupBox)
        self.sw_tracking.setObjectName(u"sw_tracking")
        self.sw_tracking.setGeometry(QRect(370, 100, 51, 21))
        self.sw_tracking.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.entry_yPos = QLineEdit(self.groupBox)
        self.entry_yPos.setObjectName(u"entry_yPos")
        self.entry_yPos.setGeometry(QRect(200, 50, 51, 20))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(280, 20, 54, 16))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(280, 100, 54, 16))
        self.sw_speedMode = QSwitchButton(self.groupBox)
        self.sw_speedMode.setObjectName(u"sw_speedMode")
        self.sw_speedMode.setGeometry(QRect(370, 60, 51, 21))
        self.sw_speedMode.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 300, 54, 16))
        self.entry_xPos = QLineEdit(self.groupBox)
        self.entry_xPos.setObjectName(u"entry_xPos")
        self.entry_xPos.setGeometry(QRect(200, 20, 51, 20))
        self.entryR_alpha0 = QLineEdit(self.groupBox)
        self.entryR_alpha0.setObjectName(u"entryR_alpha0")
        self.entryR_alpha0.setGeometry(QRect(70, 180, 51, 20))
        self.entryR_alpha0.setReadOnly(True)
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 370, 54, 16))
        self.slider_yPos = QSlider(self.groupBox)
        self.slider_yPos.setObjectName(u"slider_yPos")
        self.slider_yPos.setGeometry(QRect(10, 310, 411, 51))
        self.slider_yPos.setMinimum(1750)
        self.slider_yPos.setMaximum(4650)
        self.slider_yPos.setPageStep(1)
        self.slider_yPos.setOrientation(Qt.Orientation.Horizontal)
        self.slider_yPos.setInvertedAppearance(False)
        self.slider_yPos.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.slider_yPos.setTickInterval(20)
        self.btn_readClk = QPushButton(self.groupBox)
        self.btn_readClk.setObjectName(u"btn_readClk")
        self.btn_readClk.setGeometry(QRect(10, 140, 111, 21))
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 230, 54, 16))
        self.btn_mToSet = QPushButton(self.groupBox)
        self.btn_mToSet.setObjectName(u"btn_mToSet")
        self.btn_mToSet.setGeometry(QRect(140, 110, 111, 51))
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(280, 180, 71, 16))
        self.sw_disEnJ13 = QSwitchButton(self.groupBox)
        self.sw_disEnJ13.setObjectName(u"sw_disEnJ13")
        self.sw_disEnJ13.setGeometry(QRect(370, 140, 51, 21))
        self.sw_disEnJ13.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.cBox_armDir = QComboBox(self.groupBox)
        self.cBox_armDir.addItem("")
        self.cBox_armDir.addItem("")
        self.cBox_armDir.addItem("")
        self.cBox_armDir.addItem("")
        self.cBox_armDir.setObjectName(u"cBox_armDir")
        self.cBox_armDir.setGeometry(QRect(200, 180, 51, 20))
        self.line_5 = QFrame(self.groupBox)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 286, 411, 16))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.groupBox)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(10, 356, 411, 16))
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_7 = QFrame(self.groupBox)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 426, 411, 16))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_8 = QFrame(self.groupBox)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(10, 496, 411, 16))
        self.line_8.setFrameShape(QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_9 = QFrame(self.groupBox)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(10, 566, 411, 16))
        self.line_9.setFrameShape(QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_10 = QFrame(self.groupBox)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(10, 216, 411, 16))
        self.line_10.setStyleSheet(u"")
        self.line_10.setFrameShape(QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_11 = QFrame(self.groupBox)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(10, 636, 411, 16))
        self.line_11.setFrameShape(QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_slider_xPos = QLabel(self.groupBox)
        self.label_slider_xPos.setObjectName(u"label_slider_xPos")
        self.label_slider_xPos.setGeometry(QRect(360, 230, 54, 16))
        self.label_slider_xPos.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_slider_yPos = QLabel(self.groupBox)
        self.label_slider_yPos.setObjectName(u"label_slider_yPos")
        self.label_slider_yPos.setGeometry(QRect(360, 300, 54, 16))
        self.label_slider_yPos.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_slider_zPos = QLabel(self.groupBox)
        self.label_slider_zPos.setObjectName(u"label_slider_zPos")
        self.label_slider_zPos.setGeometry(QRect(360, 370, 54, 16))
        self.label_slider_zPos.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_slider_stepSize = QLabel(self.groupBox)
        self.label_slider_stepSize.setObjectName(u"label_slider_stepSize")
        self.label_slider_stepSize.setGeometry(QRect(360, 440, 54, 16))
        self.label_slider_stepSize.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_slider_speedX = QLabel(self.groupBox)
        self.label_slider_speedX.setObjectName(u"label_slider_speedX")
        self.label_slider_speedX.setGeometry(QRect(360, 510, 54, 16))
        self.label_slider_speedX.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_slider_speedY = QLabel(self.groupBox)
        self.label_slider_speedY.setObjectName(u"label_slider_speedY")
        self.label_slider_speedY.setGeometry(QRect(360, 580, 54, 16))
        self.label_slider_speedY.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.entryR_j4Clk = QLineEdit(self.groupBox)
        self.entryR_j4Clk.setObjectName(u"entryR_j4Clk")
        self.entryR_j4Clk.setGeometry(QRect(70, 110, 51, 20))
        self.entryR_j4Clk.setReadOnly(True)
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 110, 54, 16))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(470, 10, 591, 231))
        self.label_26 = QLabel(self.groupBox_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(40, 90, 54, 16))
        self.label_37 = QLabel(self.groupBox_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(20, 60, 121, 16))
        self.label_28 = QLabel(self.groupBox_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(270, 90, 54, 16))
        self.sw_tiltEnd = QSwitchButton(self.groupBox_3)
        self.sw_tiltEnd.setObjectName(u"sw_tiltEnd")
        self.sw_tiltEnd.setGeometry(QRect(300, 30, 51, 21))
        self.sw_tiltEnd.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.btn_toTrayGrab = QPushButton(self.groupBox_3)
        self.btn_toTrayGrab.setObjectName(u"btn_toTrayGrab")
        self.btn_toTrayGrab.setGeometry(QRect(130, 190, 91, 24))
        self.cBox_chooseVA = QComboBox(self.groupBox_3)
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.addItem("")
        self.cBox_chooseVA.setObjectName(u"cBox_chooseVA")
        self.cBox_chooseVA.setGeometry(QRect(150, 60, 201, 22))
        self.btn_toPosFix = QPushButton(self.groupBox_3)
        self.btn_toPosFix.setObjectName(u"btn_toPosFix")
        self.btn_toPosFix.setGeometry(QRect(20, 190, 91, 24))
        self.btn_toZero = QPushButton(self.groupBox_3)
        self.btn_toZero.setObjectName(u"btn_toZero")
        self.btn_toZero.setGeometry(QRect(20, 110, 91, 24))
        self.btn_posFix2trayHover = QPushButton(self.groupBox_3)
        self.btn_posFix2trayHover.setObjectName(u"btn_posFix2trayHover")
        self.btn_posFix2trayHover.setGeometry(QRect(240, 110, 111, 24))
        self.groupBox_2 = QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(360, 30, 221, 191))
        self.btn_saveVAparams = QPushButton(self.groupBox_2)
        self.btn_saveVAparams.setObjectName(u"btn_saveVAparams")
        self.btn_saveVAparams.setGeometry(QRect(10, 140, 201, 41))
        self.label_33 = QLabel(self.groupBox_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(120, 50, 54, 16))
        self.label_35 = QLabel(self.groupBox_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 80, 54, 16))
        self.entry_m3Vel = QLineEdit(self.groupBox_2)
        self.entry_m3Vel.setObjectName(u"entry_m3Vel")
        self.entry_m3Vel.setGeometry(QRect(60, 80, 41, 20))
        self.label_34 = QLabel(self.groupBox_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(120, 80, 54, 16))
        self.label_30 = QLabel(self.groupBox_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 20, 54, 16))
        self.label_32 = QLabel(self.groupBox_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 50, 54, 16))
        self.entry_m2Acc = QLineEdit(self.groupBox_2)
        self.entry_m2Acc.setObjectName(u"entry_m2Acc")
        self.entry_m2Acc.setGeometry(QRect(170, 50, 41, 20))
        self.entry_m1Vel = QLineEdit(self.groupBox_2)
        self.entry_m1Vel.setObjectName(u"entry_m1Vel")
        self.entry_m1Vel.setGeometry(QRect(60, 20, 41, 20))
        self.entry_m2Vel = QLineEdit(self.groupBox_2)
        self.entry_m2Vel.setObjectName(u"entry_m2Vel")
        self.entry_m2Vel.setGeometry(QRect(60, 50, 41, 20))
        self.cBox_modifyVA = QComboBox(self.groupBox_2)
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.addItem("")
        self.cBox_modifyVA.setObjectName(u"cBox_modifyVA")
        self.cBox_modifyVA.setGeometry(QRect(50, 110, 161, 22))
        self.label_36 = QLabel(self.groupBox_2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 110, 31, 16))
        self.label_31 = QLabel(self.groupBox_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(120, 20, 54, 16))
        self.entry_m1Acc = QLineEdit(self.groupBox_2)
        self.entry_m1Acc.setObjectName(u"entry_m1Acc")
        self.entry_m1Acc.setGeometry(QRect(170, 20, 41, 20))
        self.entry_m3Acc = QLineEdit(self.groupBox_2)
        self.entry_m3Acc.setObjectName(u"entry_m3Acc")
        self.entry_m3Acc.setGeometry(QRect(170, 80, 41, 20))
        self.label_27 = QLabel(self.groupBox_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(150, 90, 54, 16))
        self.btn_toTrayHover = QPushButton(self.groupBox_3)
        self.btn_toTrayHover.setObjectName(u"btn_toTrayHover")
        self.btn_toTrayHover.setGeometry(QRect(130, 110, 91, 24))
        self.btn_toTrackBegin = QPushButton(self.groupBox_3)
        self.btn_toTrackBegin.setObjectName(u"btn_toTrackBegin")
        self.btn_toTrackBegin.setGeometry(QRect(20, 150, 91, 24))
        self.btn_toTrayPlace = QPushButton(self.groupBox_3)
        self.btn_toTrayPlace.setObjectName(u"btn_toTrayPlace")
        self.btn_toTrayPlace.setGeometry(QRect(130, 150, 91, 24))
        self.label_29 = QLabel(self.groupBox_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 30, 111, 16))
        self.line_4 = QFrame(self.groupBox_3)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 46, 331, 20))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.groupBox_13 = QGroupBox(self.tab)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(470, 440, 211, 221))
        self.entry_J_clk = QLineEdit(self.groupBox_13)
        self.entry_J_clk.setObjectName(u"entry_J_clk")
        self.entry_J_clk.setGeometry(QRect(130, 120, 68, 22))
        self.label_71 = QLabel(self.groupBox_13)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(20, 90, 101, 16))
        self.btn_moveJ = QPushButton(self.groupBox_13)
        self.btn_moveJ.setObjectName(u"btn_moveJ")
        self.btn_moveJ.setGeometry(QRect(20, 160, 181, 41))
        self.label_44 = QLabel(self.groupBox_13)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 30, 101, 16))
        self.cBox_chooseJ = QComboBox(self.groupBox_13)
        self.cBox_chooseJ.addItem("")
        self.cBox_chooseJ.addItem("")
        self.cBox_chooseJ.addItem("")
        self.cBox_chooseJ.addItem("")
        self.cBox_chooseJ.setObjectName(u"cBox_chooseJ")
        self.cBox_chooseJ.setGeometry(QRect(130, 30, 68, 22))
        self.label_45 = QLabel(self.groupBox_13)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(20, 60, 101, 16))
        self.entry_J_acc = QLineEdit(self.groupBox_13)
        self.entry_J_acc.setObjectName(u"entry_J_acc")
        self.entry_J_acc.setGeometry(QRect(130, 90, 68, 22))
        self.entry_J_vel = QLineEdit(self.groupBox_13)
        self.entry_J_vel.setObjectName(u"entry_J_vel")
        self.entry_J_vel.setGeometry(QRect(130, 60, 68, 22))
        self.label_72 = QLabel(self.groupBox_13)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(20, 120, 101, 16))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setAutoFillBackground(True)
        self.groupBox_6 = QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(0, 30, 341, 271))
        self.frameLabel = QLabel(self.groupBox_6)
        self.frameLabel.setObjectName(u"frameLabel")
        self.frameLabel.setGeometry(QRect(10, 20, 320, 240))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frameLabel.sizePolicy().hasHeightForWidth())
        self.frameLabel.setSizePolicy(sizePolicy1)
        self.frameLabel.setMinimumSize(QSize(320, 240))
        self.frameLabel.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.groupBox_7 = QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(380, 30, 341, 271))
        self.frameLabel_2 = QLabel(self.groupBox_7)
        self.frameLabel_2.setObjectName(u"frameLabel_2")
        self.frameLabel_2.setGeometry(QRect(10, 20, 320, 240))
        sizePolicy1.setHeightForWidth(self.frameLabel_2.sizePolicy().hasHeightForWidth())
        self.frameLabel_2.setSizePolicy(sizePolicy1)
        self.frameLabel_2.setMinimumSize(QSize(320, 240))
        self.frameLabel_2.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.groupBox_8 = QGroupBox(self.tab_2)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(730, 30, 341, 271))
        self.frameLabel_3 = QLabel(self.groupBox_8)
        self.frameLabel_3.setObjectName(u"frameLabel_3")
        self.frameLabel_3.setGeometry(QRect(10, 20, 320, 240))
        sizePolicy1.setHeightForWidth(self.frameLabel_3.sizePolicy().hasHeightForWidth())
        self.frameLabel_3.setSizePolicy(sizePolicy1)
        self.frameLabel_3.setMinimumSize(QSize(320, 240))
        self.frameLabel_3.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.groupBox_10 = QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(360, 330, 451, 51))
        self.label_46 = QLabel(self.groupBox_10)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 20, 21, 16))
        self.entry_pid1_Kp = QLineEdit(self.groupBox_10)
        self.entry_pid1_Kp.setObjectName(u"entry_pid1_Kp")
        self.entry_pid1_Kp.setGeometry(QRect(30, 20, 51, 20))
        self.entry_pid1_Ki = QLineEdit(self.groupBox_10)
        self.entry_pid1_Ki.setObjectName(u"entry_pid1_Ki")
        self.entry_pid1_Ki.setGeometry(QRect(130, 20, 51, 20))
        self.label_47 = QLabel(self.groupBox_10)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(110, 20, 21, 16))
        self.entry_pid1_Kd = QLineEdit(self.groupBox_10)
        self.entry_pid1_Kd.setObjectName(u"entry_pid1_Kd")
        self.entry_pid1_Kd.setGeometry(QRect(230, 20, 51, 20))
        self.label_48 = QLabel(self.groupBox_10)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(210, 20, 21, 16))
        self.btn_updatePID1 = QPushButton(self.groupBox_10)
        self.btn_updatePID1.setObjectName(u"btn_updatePID1")
        self.btn_updatePID1.setGeometry(QRect(320, 20, 111, 21))
        self.label_52 = QLabel(self.tab_2)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(830, 310, 61, 16))
        self.cBox_targetColor = QComboBox(self.tab_2)
        self.cBox_targetColor.addItem("")
        self.cBox_targetColor.addItem("")
        self.cBox_targetColor.addItem("")
        self.cBox_targetColor.setObjectName(u"cBox_targetColor")
        self.cBox_targetColor.setEnabled(True)
        self.cBox_targetColor.setGeometry(QRect(900, 310, 71, 22))
        self.cBox_targetColor.setEditable(False)
        self.cBox_targetObject = QComboBox(self.tab_2)
        self.cBox_targetObject.addItem("")
        self.cBox_targetObject.addItem("")
        self.cBox_targetObject.setObjectName(u"cBox_targetObject")
        self.cBox_targetObject.setGeometry(QRect(900, 350, 71, 22))
        self.label_53 = QLabel(self.tab_2)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(830, 350, 61, 16))
        self.label_54 = QLabel(self.tab_2)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(660, 310, 54, 16))
        self.sw_tracking_2 = QSwitchButton(self.tab_2)
        self.sw_tracking_2.setObjectName(u"sw_tracking_2")
        self.sw_tracking_2.setGeometry(QRect(740, 310, 51, 21))
        self.sw_tracking_2.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.groupBox_11 = QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(360, 380, 451, 51))
        self.label_49 = QLabel(self.groupBox_11)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 20, 21, 16))
        self.entry_pid2_Kp = QLineEdit(self.groupBox_11)
        self.entry_pid2_Kp.setObjectName(u"entry_pid2_Kp")
        self.entry_pid2_Kp.setGeometry(QRect(30, 20, 51, 20))
        self.entry_pid2_Ki = QLineEdit(self.groupBox_11)
        self.entry_pid2_Ki.setObjectName(u"entry_pid2_Ki")
        self.entry_pid2_Ki.setGeometry(QRect(130, 20, 51, 20))
        self.label_50 = QLabel(self.groupBox_11)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(110, 20, 21, 16))
        self.entry_pid2_Kd = QLineEdit(self.groupBox_11)
        self.entry_pid2_Kd.setObjectName(u"entry_pid2_Kd")
        self.entry_pid2_Kd.setGeometry(QRect(230, 20, 51, 20))
        self.label_51 = QLabel(self.groupBox_11)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(210, 20, 21, 16))
        self.btn_updatePID2 = QPushButton(self.groupBox_11)
        self.btn_updatePID2.setObjectName(u"btn_updatePID2")
        self.btn_updatePID2.setGeometry(QRect(320, 20, 111, 21))
        self.slider_hMin = QSlider(self.tab_2)
        self.slider_hMin.setObjectName(u"slider_hMin")
        self.slider_hMin.setGeometry(QRect(460, 440, 591, 21))
        self.slider_hMin.setMaximum(179)
        self.slider_hMin.setOrientation(Qt.Orientation.Horizontal)
        self.cBox_Red1or2 = QComboBox(self.tab_2)
        self.cBox_Red1or2.addItem("")
        self.cBox_Red1or2.addItem("")
        self.cBox_Red1or2.setObjectName(u"cBox_Red1or2")
        self.cBox_Red1or2.setEnabled(True)
        self.cBox_Red1or2.setGeometry(QRect(980, 310, 71, 22))
        self.cBox_Red1or2.setEditable(False)
        self.label_55 = QLabel(self.tab_2)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(360, 440, 41, 16))
        self.entry_hMin = QLineEdit(self.tab_2)
        self.entry_hMin.setObjectName(u"entry_hMin")
        self.entry_hMin.setGeometry(QRect(410, 440, 41, 20))
        self.slider_hMax = QSlider(self.tab_2)
        self.slider_hMax.setObjectName(u"slider_hMax")
        self.slider_hMax.setGeometry(QRect(460, 470, 591, 21))
        self.slider_hMax.setMaximum(179)
        self.slider_hMax.setValue(179)
        self.slider_hMax.setOrientation(Qt.Orientation.Horizontal)
        self.label_56 = QLabel(self.tab_2)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(360, 470, 41, 16))
        self.entry_hMax = QLineEdit(self.tab_2)
        self.entry_hMax.setObjectName(u"entry_hMax")
        self.entry_hMax.setGeometry(QRect(410, 470, 41, 20))
        self.slider_sMin = QSlider(self.tab_2)
        self.slider_sMin.setObjectName(u"slider_sMin")
        self.slider_sMin.setGeometry(QRect(460, 520, 591, 21))
        self.slider_sMin.setMaximum(255)
        self.slider_sMin.setOrientation(Qt.Orientation.Horizontal)
        self.label_57 = QLabel(self.tab_2)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(360, 520, 41, 16))
        self.entry_sMin = QLineEdit(self.tab_2)
        self.entry_sMin.setObjectName(u"entry_sMin")
        self.entry_sMin.setGeometry(QRect(410, 520, 41, 20))
        self.slider_sMax = QSlider(self.tab_2)
        self.slider_sMax.setObjectName(u"slider_sMax")
        self.slider_sMax.setGeometry(QRect(460, 550, 591, 21))
        self.slider_sMax.setMaximum(255)
        self.slider_sMax.setValue(255)
        self.slider_sMax.setOrientation(Qt.Orientation.Horizontal)
        self.entry_sMax = QLineEdit(self.tab_2)
        self.entry_sMax.setObjectName(u"entry_sMax")
        self.entry_sMax.setGeometry(QRect(410, 550, 41, 20))
        self.label_58 = QLabel(self.tab_2)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(360, 550, 41, 16))
        self.slider_vMin = QSlider(self.tab_2)
        self.slider_vMin.setObjectName(u"slider_vMin")
        self.slider_vMin.setGeometry(QRect(460, 600, 591, 21))
        self.slider_vMin.setMaximum(255)
        self.slider_vMin.setOrientation(Qt.Orientation.Horizontal)
        self.entry_vMin = QLineEdit(self.tab_2)
        self.entry_vMin.setObjectName(u"entry_vMin")
        self.entry_vMin.setGeometry(QRect(410, 600, 41, 20))
        self.label_59 = QLabel(self.tab_2)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(360, 600, 41, 16))
        self.slider_vMax = QSlider(self.tab_2)
        self.slider_vMax.setObjectName(u"slider_vMax")
        self.slider_vMax.setGeometry(QRect(460, 630, 591, 21))
        self.slider_vMax.setMaximum(255)
        self.slider_vMax.setValue(255)
        self.slider_vMax.setOrientation(Qt.Orientation.Horizontal)
        self.entry_vMax = QLineEdit(self.tab_2)
        self.entry_vMax.setObjectName(u"entry_vMax")
        self.entry_vMax.setGeometry(QRect(410, 630, 41, 20))
        self.label_60 = QLabel(self.tab_2)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(360, 630, 41, 16))
        self.btn_resetHSV = QPushButton(self.tab_2)
        self.btn_resetHSV.setObjectName(u"btn_resetHSV")
        self.btn_resetHSV.setGeometry(QRect(830, 390, 221, 41))
        self.slider_centerX = QSlider(self.tab_2)
        self.slider_centerX.setObjectName(u"slider_centerX")
        self.slider_centerX.setGeometry(QRect(19, 10, 301, 21))
        self.slider_centerX.setMaximum(640)
        self.slider_centerX.setPageStep(1)
        self.slider_centerX.setValue(304)
        self.slider_centerX.setOrientation(Qt.Orientation.Horizontal)
        self.slider_centerY = QSlider(self.tab_2)
        self.slider_centerY.setObjectName(u"slider_centerY")
        self.slider_centerY.setGeometry(QRect(350, 50, 21, 241))
        self.slider_centerY.setMaximum(480)
        self.slider_centerY.setPageStep(1)
        self.slider_centerY.setValue(238)
        self.slider_centerY.setOrientation(Qt.Orientation.Vertical)
        self.slider_centerY.setInvertedAppearance(True)
        self.groupBox_9 = QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(0, 310, 351, 291))
        self.logText_2 = QTextBrowser(self.groupBox_9)
        self.logText_2.setObjectName(u"logText_2")
        self.logText_2.setGeometry(QRect(10, 20, 331, 261))
        self.btn_rebootVision = QPushButton(self.tab_2)
        self.btn_rebootVision.setObjectName(u"btn_rebootVision")
        self.btn_rebootVision.setGeometry(QRect(90, 620, 151, 25))
        self.check_show1 = QCheckBox(self.tab_2)
        self.check_show1.setObjectName(u"check_show1")
        self.check_show1.setGeometry(QRect(330, 10, 79, 20))
        self.check_show2 = QCheckBox(self.tab_2)
        self.check_show2.setObjectName(u"check_show2")
        self.check_show2.setGeometry(QRect(660, 10, 79, 20))
        self.check_show3 = QCheckBox(self.tab_2)
        self.check_show3.setObjectName(u"check_show3")
        self.check_show3.setGeometry(QRect(1010, 10, 61, 20))
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(360, 310, 81, 17))
        self.label_23 = QLabel(self.tab_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(440, 310, 21, 17))
        self.entry_blueDeltaX = QLineEdit(self.tab_2)
        self.entry_blueDeltaX.setObjectName(u"entry_blueDeltaX")
        self.entry_blueDeltaX.setGeometry(QRect(460, 310, 41, 25))
        self.entry_blueDeltaY = QLineEdit(self.tab_2)
        self.entry_blueDeltaY.setObjectName(u"entry_blueDeltaY")
        self.entry_blueDeltaY.setGeometry(QRect(530, 310, 41, 25))
        self.label_24 = QLabel(self.tab_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(510, 310, 21, 17))
        self.btn_saveblueDelta = QPushButton(self.tab_2)
        self.btn_saveblueDelta.setObjectName(u"btn_saveblueDelta")
        self.btn_saveblueDelta.setGeometry(QRect(590, 310, 51, 25))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tab_3.setAutoFillBackground(True)
        self.label_61 = QLabel(self.tab_3)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(30, 190, 61, 16))
        self.cBox_subTaskNum = QComboBox(self.tab_3)
        self.cBox_subTaskNum.addItem("")
        self.cBox_subTaskNum.addItem("")
        self.cBox_subTaskNum.addItem("")
        self.cBox_subTaskNum.addItem("")
        self.cBox_subTaskNum.addItem("")
        self.cBox_subTaskNum.setObjectName(u"cBox_subTaskNum")
        self.cBox_subTaskNum.setGeometry(QRect(100, 190, 201, 22))
        self.cBox_colorOrder = QComboBox(self.tab_3)
        self.cBox_colorOrder.addItem("")
        self.cBox_colorOrder.addItem("")
        self.cBox_colorOrder.addItem("")
        self.cBox_colorOrder.addItem("")
        self.cBox_colorOrder.addItem("")
        self.cBox_colorOrder.addItem("")
        self.cBox_colorOrder.setObjectName(u"cBox_colorOrder")
        self.cBox_colorOrder.setGeometry(QRect(100, 150, 201, 22))
        self.label_62 = QLabel(self.tab_3)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(30, 150, 61, 16))
        self.btn_taskStart = QPushButton(self.tab_3)
        self.btn_taskStart.setObjectName(u"btn_taskStart")
        self.btn_taskStart.setGeometry(QRect(30, 230, 271, 71))
        self.btn_cancelReached = QPushButton(self.tab_3)
        self.btn_cancelReached.setObjectName(u"btn_cancelReached")
        self.btn_cancelReached.setGeometry(QRect(320, 150, 271, 61))
        self.btn_taskCancel = QPushButton(self.tab_3)
        self.btn_taskCancel.setObjectName(u"btn_taskCancel")
        self.btn_taskCancel.setGeometry(QRect(320, 230, 271, 71))
        self.label_63 = QLabel(self.tab_3)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(30, 340, 71, 16))
        self.entry_carRelX = QLineEdit(self.tab_3)
        self.entry_carRelX.setObjectName(u"entry_carRelX")
        self.entry_carRelX.setGeometry(QRect(190, 340, 113, 20))
        self.entry_carRelY = QLineEdit(self.tab_3)
        self.entry_carRelY.setObjectName(u"entry_carRelY")
        self.entry_carRelY.setGeometry(QRect(190, 370, 113, 20))
        self.label_64 = QLabel(self.tab_3)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(30, 370, 71, 16))
        self.entry_carRelT = QLineEdit(self.tab_3)
        self.entry_carRelT.setObjectName(u"entry_carRelT")
        self.entry_carRelT.setGeometry(QRect(190, 400, 113, 20))
        self.label_65 = QLabel(self.tab_3)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(30, 400, 71, 16))
        self.btn_carRelMove = QPushButton(self.tab_3)
        self.btn_carRelMove.setObjectName(u"btn_carRelMove")
        self.btn_carRelMove.setGeometry(QRect(30, 430, 271, 51))
        self.entryR_isCarReached = QLineEdit(self.tab_3)
        self.entryR_isCarReached.setObjectName(u"entryR_isCarReached")
        self.entryR_isCarReached.setGeometry(QRect(190, 500, 113, 20))
        self.entryR_isCarReached.setReadOnly(True)
        self.label_66 = QLabel(self.tab_3)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(30, 500, 91, 16))
        self.label_67 = QLabel(self.tab_3)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(320, 100, 81, 16))
        self.sw_carPosFix = QSwitchButton(self.tab_3)
        self.sw_carPosFix.setObjectName(u"sw_carPosFix")
        self.sw_carPosFix.setGeometry(QRect(540, 100, 51, 21))
        self.sw_carPosFix.setStyleSheet(u"background-color: rgb(85, 255, 0);")
        self.groupBox_12 = QGroupBox(self.tab_3)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(610, 140, 451, 341))
        self.logText_3 = QTextBrowser(self.groupBox_12)
        self.logText_3.setObjectName(u"logText_3")
        self.logText_3.setGeometry(QRect(10, 20, 431, 311))
        self.entry_carRotateA = QLineEdit(self.tab_3)
        self.entry_carRotateA.setObjectName(u"entry_carRotateA")
        self.entry_carRotateA.setGeometry(QRect(480, 340, 113, 20))
        self.label_68 = QLabel(self.tab_3)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(320, 370, 141, 16))
        self.entry_carRotateS = QLineEdit(self.tab_3)
        self.entry_carRotateS.setObjectName(u"entry_carRotateS")
        self.entry_carRotateS.setGeometry(QRect(480, 370, 113, 20))
        self.label_69 = QLabel(self.tab_3)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(320, 340, 131, 16))
        self.label_16 = QLabel(self.tab_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(480, 320, 111, 20))
        self.btn_carRotate = QPushButton(self.tab_3)
        self.btn_carRotate.setObjectName(u"btn_carRotate")
        self.btn_carRotate.setGeometry(QRect(320, 430, 271, 51))
        self.entryR_isCarRotateReached = QLineEdit(self.tab_3)
        self.entryR_isCarRotateReached.setObjectName(u"entryR_isCarRotateReached")
        self.entryR_isCarRotateReached.setGeometry(QRect(480, 500, 113, 20))
        self.entryR_isCarRotateReached.setReadOnly(True)
        self.label_70 = QLabel(self.tab_3)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(320, 500, 131, 16))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tab_4.setAutoFillBackground(False)
        self.tab_4.setStyleSheet(u"background-color: rgb(170, 0, 255);")
        self.verticalLayout_3 = QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.btn_readQR = QPushButton(self.tab_4)
        self.btn_readQR.setObjectName(u"btn_readQR")
        self.btn_readQR.setMinimumSize(QSize(201, 101))
        self.btn_readQR.setStyleSheet(u"font: 36pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(255, 85, 0);")

        self.horizontalLayout_2.addWidget(self.btn_readQR)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.label_19 = QLabel(self.tab_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setMinimumSize(QSize(251, 101))
        self.label_19.setStyleSheet(u"font: 36pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(255, 85, 0);")
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.label_19)

        self.entry_tableHeight = QLineEdit(self.tab_4)
        self.entry_tableHeight.setObjectName(u"entry_tableHeight")
        sizePolicy1.setHeightForWidth(self.entry_tableHeight.sizePolicy().hasHeightForWidth())
        self.entry_tableHeight.setSizePolicy(sizePolicy1)
        self.entry_tableHeight.setMinimumSize(QSize(191, 101))
        self.entry_tableHeight.setMaximumSize(QSize(130, 16777215))
        self.entry_tableHeight.setStyleSheet(u"font: 36pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(255, 85, 0);")

        self.horizontalLayout_2.addWidget(self.entry_tableHeight)

        self.btn_saveHeight = QPushButton(self.tab_4)
        self.btn_saveHeight.setObjectName(u"btn_saveHeight")
        self.btn_saveHeight.setMinimumSize(QSize(201, 101))
        self.btn_saveHeight.setStyleSheet(u"font: 36pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(255, 85, 0);")

        self.horizontalLayout_2.addWidget(self.btn_saveHeight)


        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.verticalSpacer = QSpacerItem(20, 25, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer)

        self.label_QR_Data = QLabel(self.tab_4)
        self.label_QR_Data.setObjectName(u"label_QR_Data")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_QR_Data.sizePolicy().hasHeightForWidth())
        self.label_QR_Data.setSizePolicy(sizePolicy2)
        self.label_QR_Data.setMinimumSize(QSize(0, 271))
        self.label_QR_Data.setMaximumSize(QSize(16777215, 300))
        font = QFont()
        font.setFamilies([u"Microsoft YaHei UI"])
        font.setPointSize(200)
        font.setBold(False)
        font.setItalic(False)
        self.label_QR_Data.setFont(font)
        self.label_QR_Data.setStyleSheet(u"font: 200pt \"Microsoft YaHei UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_QR_Data.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_QR_Data)

        self.verticalSpacer_2 = QSpacerItem(20, 39, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)

        self.verticalLayout_3.addItem(self.verticalSpacer_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalSpacer_3 = QSpacerItem(20, 28, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_3)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.btn_toStartPos = QPushButton(self.tab_4)
        self.btn_toStartPos.setObjectName(u"btn_toStartPos")
        self.btn_toStartPos.setMinimumSize(QSize(251, 121))
        self.btn_toStartPos.setStyleSheet(u"font: 36pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(255, 85, 0);")

        self.horizontalLayout_3.addWidget(self.btn_toStartPos)

        self.btn_toDebugPos = QPushButton(self.tab_4)
        self.btn_toDebugPos.setObjectName(u"btn_toDebugPos")
        self.btn_toDebugPos.setMinimumSize(QSize(251, 121))
        self.btn_toDebugPos.setStyleSheet(u"font: 36pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(255, 85, 0);")

        self.horizontalLayout_3.addWidget(self.btn_toDebugPos)

        self.btn_fullScreen = QPushButton(self.tab_4)
        self.btn_fullScreen.setObjectName(u"btn_fullScreen")
        self.btn_fullScreen.setMinimumSize(QSize(251, 121))
        self.btn_fullScreen.setStyleSheet(u"font: 36pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(255, 85, 0);")

        self.horizontalLayout_3.addWidget(self.btn_fullScreen)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)


        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_3)

        self.btn_GO = QPushButton(self.tab_4)
        self.btn_GO.setObjectName(u"btn_GO")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.btn_GO.sizePolicy().hasHeightForWidth())
        self.btn_GO.setSizePolicy(sizePolicy3)
        self.btn_GO.setMinimumSize(QSize(261, 200))
        self.btn_GO.setStyleSheet(u"font: 72pt \"Microsoft YaHei UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 194, 0);")

        self.horizontalLayout_4.addWidget(self.btn_GO)


        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.tabWidget.addTab(self.tab_4, "")

        self.verticalLayout.addWidget(self.tabWidget)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.connectionLabel = QLabel(self.scrollAreaWidgetContents)
        self.connectionLabel.setObjectName(u"connectionLabel")
        self.connectionLabel.setMinimumSize(QSize(81, 16))
        self.connectionLabel.setMaximumSize(QSize(16777215, 16))
        self.connectionLabel.setStyleSheet(u"color: rgb(255, 0, 0);")

        self.horizontalLayout.addWidget(self.connectionLabel)

        self.sysLabel = QLabel(self.scrollAreaWidgetContents)
        self.sysLabel.setObjectName(u"sysLabel")
        self.sysLabel.setMinimumSize(QSize(231, 16))
        self.sysLabel.setMaximumSize(QSize(16777215, 16))
        self.sysLabel.setStyleSheet(u"color: rgb(0, 0, 255);")

        self.horizontalLayout.addWidget(self.sysLabel)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GreenLightV2_CTRL", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u8235\u673a\u63a7\u5236", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u6258\u76d8\u4e0a\u8235\u673a(012\u9006\u65f6\u9488\u5206\u5e03)\uff1a</p></body></html>", None))
        self.cBox_setPosSevro4.setItemText(0, QCoreApplication.translate("MainWindow", u"1\u53f7\u4f4d(\u521d\u59cb)", None))
        self.cBox_setPosSevro4.setItemText(1, QCoreApplication.translate("MainWindow", u"0\u53f7\u4f4d", None))
        self.cBox_setPosSevro4.setItemText(2, QCoreApplication.translate("MainWindow", u"2\u53f7\u4f4d", None))
        self.cBox_setPosSevro4.setItemText(3, QCoreApplication.translate("MainWindow", u"3\u907f\u8ba9\u4f4d\u7f6eDir2", None))
        self.cBox_setPosSevro4.setItemText(4, QCoreApplication.translate("MainWindow", u"4\u907f\u8ba9\u4f4d\u7f6eDir3", None))

        self.entry_servoDegree.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.btn_moveServo.setText(QCoreApplication.translate("MainWindow", u"\u8235\u673a\u8fd0\u52a8", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"\u5939\u722a\u5939\u7d27", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"\u8235\u673a\u7f16\u53f7\uff1a", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"\u6444\u50cf\u5934\u524d\u8f6c", None))
        self.cBox_setPosSevro3.setItemText(0, QCoreApplication.translate("MainWindow", u"0\u521d\u59cb\u4f4d\u7f6e", None))
        self.cBox_setPosSevro3.setItemText(1, QCoreApplication.translate("MainWindow", u"1\u987a\u65f6\u948890\u5ea6", None))
        self.cBox_setPosSevro3.setItemText(2, QCoreApplication.translate("MainWindow", u"2\u5de5\u4f5c\u4f4d\u7f6e(\u987a180)", None))
        self.cBox_setPosSevro3.setItemText(3, QCoreApplication.translate("MainWindow", u"3\u907f\u8ba9\u4f4d\u7f6eDir2", None))
        self.cBox_setPosSevro3.setItemText(4, QCoreApplication.translate("MainWindow", u"4\u907f\u8ba9\u4f4d\u7f6eDir3", None))

        self.label_39.setText(QCoreApplication.translate("MainWindow", u"\u89d2\u5ea6\uff1a", None))
        self.cBox_chooseServo.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.cBox_chooseServo.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.cBox_chooseServo.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.cBox_chooseServo.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))

        self.label_42.setText(QCoreApplication.translate("MainWindow", u"\u6258\u76d8\u4e0b\u8235\u673a\uff1a", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c\u65e5\u5fd7", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u63a7\u5236", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u6574Y\u8f74\u901f\u5ea6", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u671d\u5411\u7f16\u53f7\uff1a", None))
        self.entryR_j3Clk.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.entryR_j1Clk.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"J1\u8109\u51b2\uff1a", None))
        self.entry_zPos.setText(QCoreApplication.translate("MainWindow", u"199", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Z\u8f74\u4f4d\u7f6e\uff1a", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"X\u8f74\u4f4d\u7f6e\uff1a", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u6574X\u8f74\u901f\u5ea6", None))
        self.entryR_j2Clk.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5e95\u5ea7\u8f6c\u89d2\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"J3\u8109\u51b2\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Y\u8f74\u4f4d\u7f6e\uff1a", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6\u6a21\u5f0f", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"J2\u8109\u51b2\uff1a", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u5931\u80fd(J1~3)", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u6574\u6b65\u8fdb\u503c", None))
        self.entry_yPos.setText(QCoreApplication.translate("MainWindow", u"175", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u65f6\u63a7\u5236", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u89c9\u8ddf\u8e2a", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u6574Y\u8f74", None))
        self.entry_xPos.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.entryR_alpha0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u6574Z\u8f74", None))
        self.btn_readClk.setText(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6\u8109\u51b2", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u6574X\u8f74", None))
        self.btn_mToSet.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u52a8\u81f3\u8bbe\u5b9a\u4f4d\u7f6e", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u5931\u80fd(J1~4)", None))
        self.cBox_armDir.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.cBox_armDir.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.cBox_armDir.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.cBox_armDir.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))

        self.label_slider_xPos.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_slider_yPos.setText(QCoreApplication.translate("MainWindow", u"175.0", None))
        self.label_slider_zPos.setText(QCoreApplication.translate("MainWindow", u"199.0", None))
        self.label_slider_stepSize.setText(QCoreApplication.translate("MainWindow", u"0.080", None))
        self.label_slider_speedX.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_slider_speedY.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.entryR_j4Clk.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"J4\u8109\u51b2\uff1a", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u4f4d\u59ff", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">\u76f8\u5bf9</p></body></html>", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6\u52a0\u901f\u5ea6\u53c2\u6570\u9009\u62e9\uff1a", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">\u7279\u6b8a</p></body></html>", None))
        self.btn_toTrayGrab.setText(QCoreApplication.translate("MainWindow", u"\u6258\u76d8\u5939\u53d6\u70b9", None))
        self.cBox_chooseVA.setItemText(0, QCoreApplication.translate("MainWindow", u"ALLDEFAULT", None))
        self.cBox_chooseVA.setItemText(1, QCoreApplication.translate("MainWindow", u"ZERO", None))
        self.cBox_chooseVA.setItemText(2, QCoreApplication.translate("MainWindow", u"ZERO_ChangeDir", None))
        self.cBox_chooseVA.setItemText(3, QCoreApplication.translate("MainWindow", u"DEFAULT", None))
        self.cBox_chooseVA.setItemText(4, QCoreApplication.translate("MainWindow", u"ToTrackBegin", None))
        self.cBox_chooseVA.setItemText(5, QCoreApplication.translate("MainWindow", u"ToTrayHover_Normal", None))
        self.cBox_chooseVA.setItemText(6, QCoreApplication.translate("MainWindow", u"ToTrayHover_Slow", None))
        self.cBox_chooseVA.setItemText(7, QCoreApplication.translate("MainWindow", u"ToTrayHover_Fast", None))
        self.cBox_chooseVA.setItemText(8, QCoreApplication.translate("MainWindow", u"ArmFix_ToTrayHover", None))
        self.cBox_chooseVA.setItemText(9, QCoreApplication.translate("MainWindow", u"Dir1toTrayPlace_Slow", None))
        self.cBox_chooseVA.setItemText(10, QCoreApplication.translate("MainWindow", u"Dir1toTrayPlace_Fast", None))
        self.cBox_chooseVA.setItemText(11, QCoreApplication.translate("MainWindow", u"Dir23toTrayPlace_Slow", None))
        self.cBox_chooseVA.setItemText(12, QCoreApplication.translate("MainWindow", u"Dir23toTrayPlace_Fast", None))
        self.cBox_chooseVA.setItemText(13, QCoreApplication.translate("MainWindow", u"ToTrayGrab", None))
        self.cBox_chooseVA.setItemText(14, QCoreApplication.translate("MainWindow", u"ToCirCatch_Up", None))
        self.cBox_chooseVA.setItemText(15, QCoreApplication.translate("MainWindow", u"ToCirCatch_Down", None))

        self.btn_toPosFix.setText(QCoreApplication.translate("MainWindow", u"\u8f66\u4f53\u5b9a\u4f4d\u70b9", None))
        self.btn_toZero.setText(QCoreApplication.translate("MainWindow", u"\u96f6\u70b9", None))
        self.btn_posFix2trayHover.setText(QCoreApplication.translate("MainWindow", u"\u5b9a\u4f4d\u70b9\u56de\u5230\u60ac\u505c\u70b9", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6\u52a0\u901f\u5ea6\u53c2\u6570\u4fee\u6539", None))
        self.btn_saveVAparams.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"M2_Acc:", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"M3_Vel:", None))
        self.entry_m3Vel.setText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"M3_Acc:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"M1_Vel:", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"M2_Vel:", None))
        self.entry_m2Acc.setText(QCoreApplication.translate("MainWindow", u"80", None))
        self.entry_m1Vel.setText(QCoreApplication.translate("MainWindow", u"4000", None))
        self.entry_m2Vel.setText(QCoreApplication.translate("MainWindow", u"800", None))
        self.cBox_modifyVA.setItemText(0, QCoreApplication.translate("MainWindow", u"ZERO", None))
        self.cBox_modifyVA.setItemText(1, QCoreApplication.translate("MainWindow", u"ZERO_ChangeDir", None))
        self.cBox_modifyVA.setItemText(2, QCoreApplication.translate("MainWindow", u"DEFAULT", None))
        self.cBox_modifyVA.setItemText(3, QCoreApplication.translate("MainWindow", u"ToTrackBegin", None))
        self.cBox_modifyVA.setItemText(4, QCoreApplication.translate("MainWindow", u"ToTrayHover_Normal", None))
        self.cBox_modifyVA.setItemText(5, QCoreApplication.translate("MainWindow", u"ToTrayHover_Slow", None))
        self.cBox_modifyVA.setItemText(6, QCoreApplication.translate("MainWindow", u"ToTrayHover_Fast", None))
        self.cBox_modifyVA.setItemText(7, QCoreApplication.translate("MainWindow", u"ArmFix_ToTrayHover", None))
        self.cBox_modifyVA.setItemText(8, QCoreApplication.translate("MainWindow", u"Dir1toTrayPlace_Slow", None))
        self.cBox_modifyVA.setItemText(9, QCoreApplication.translate("MainWindow", u"Dir1toTrayPlace_Fast", None))
        self.cBox_modifyVA.setItemText(10, QCoreApplication.translate("MainWindow", u"Dir23toTrayPlace_Slow", None))
        self.cBox_modifyVA.setItemText(11, QCoreApplication.translate("MainWindow", u"Dir23toTrayPlace_Fast", None))
        self.cBox_modifyVA.setItemText(12, QCoreApplication.translate("MainWindow", u"ToTrayGrab", None))
        self.cBox_modifyVA.setItemText(13, QCoreApplication.translate("MainWindow", u"ToCirCatch_Up", None))
        self.cBox_modifyVA.setItemText(14, QCoreApplication.translate("MainWindow", u"ToCirCatch_Down", None))

        self.label_36.setText(QCoreApplication.translate("MainWindow", u"\u53c2\u6570\uff1a", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"M1_Acc:", None))
        self.entry_m1Acc.setText(QCoreApplication.translate("MainWindow", u"150", None))
        self.entry_m3Acc.setText(QCoreApplication.translate("MainWindow", u"80", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">\u7edd\u5bf9</p><p align=\"center\"><br/></p></body></html>", None))
        self.btn_toTrayHover.setText(QCoreApplication.translate("MainWindow", u"\u6258\u76d8\u60ac\u505c\u70b9", None))
        self.btn_toTrackBegin.setText(QCoreApplication.translate("MainWindow", u"\u7269\u6599\u8ddf\u8e2a\u8d77\u70b9", None))
        self.btn_toTrayPlace.setText(QCoreApplication.translate("MainWindow", u"\u6258\u76d8\u653e\u7f6e\u70b9", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"\u672b\u7aef\u503e\u659c\u5b9a\u4f4d\u6a21\u5f0f", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"\u5173\u8282\u7535\u673a\u8109\u51b2\u63a7\u5236", None))
        self.entry_J_clk.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u901f\u5ea6\uff1a", None))
        self.btn_moveJ.setText(QCoreApplication.translate("MainWindow", u"\u5173\u8282\u7535\u673a\u8fd0\u52a8", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"\u7535\u673a\u7f16\u53f7\uff1a", None))
        self.cBox_chooseJ.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.cBox_chooseJ.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.cBox_chooseJ.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.cBox_chooseJ.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))

        self.label_45.setText(QCoreApplication.translate("MainWindow", u"\u901f\u5ea6\uff1a", None))
        self.entry_J_acc.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.entry_J_vel.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"\u8109\u51b2(\u6b63\u987a\u8d1f\u9006)\uff1a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u673a\u68b0\u81c2\u754c\u9762", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"1.Camera Feed", None))
        self.frameLabel.setText("")
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"2.Gauss Mask", None))
        self.frameLabel_2.setText("")
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"3.QR", None))
        self.frameLabel_3.setText("")
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"PID1\u8bbe\u5b9a\uff08\u8fdc\uff09", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Kp:", None))
        self.entry_pid1_Kp.setText(QCoreApplication.translate("MainWindow", u"16.0", None))
        self.entry_pid1_Ki.setText(QCoreApplication.translate("MainWindow", u"0.001", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Ki:", None))
        self.entry_pid1_Kd.setText(QCoreApplication.translate("MainWindow", u"5.0", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Kd:", None))
        self.btn_updatePID1.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0PID1", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"\u76ee\u6807\u989c\u8272\uff1a", None))
        self.cBox_targetColor.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7ea2\u8272", None))
        self.cBox_targetColor.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7eff\u8272", None))
        self.cBox_targetColor.setItemText(2, QCoreApplication.translate("MainWindow", u"\u84dd\u8272", None))

        self.cBox_targetObject.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7269\u6599", None))
        self.cBox_targetObject.setItemText(1, QCoreApplication.translate("MainWindow", u"\u8272\u73af", None))

        self.label_53.setText(QCoreApplication.translate("MainWindow", u"\u76ee\u6807\u5bf9\u8c61\uff1a", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u89c9\u8ddf\u8e2a", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"PID2\u8bbe\u5b9a\uff08\u8fd1\uff09", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Kp:", None))
        self.entry_pid2_Kp.setText(QCoreApplication.translate("MainWindow", u"16.0", None))
        self.entry_pid2_Ki.setText(QCoreApplication.translate("MainWindow", u"0.001", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Ki:", None))
        self.entry_pid2_Kd.setText(QCoreApplication.translate("MainWindow", u"5.0", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Kd:", None))
        self.btn_updatePID2.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0PID2", None))
        self.cBox_Red1or2.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7ea2\u82721", None))
        self.cBox_Red1or2.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7ea2\u82722", None))

        self.label_55.setText(QCoreApplication.translate("MainWindow", u"H Min:", None))
        self.entry_hMin.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"H Max:", None))
        self.entry_hMax.setText(QCoreApplication.translate("MainWindow", u"179", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"S Min:", None))
        self.entry_sMin.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.entry_sMax.setText(QCoreApplication.translate("MainWindow", u"255", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"S Max:", None))
        self.entry_vMin.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"V Min:", None))
        self.entry_vMax.setText(QCoreApplication.translate("MainWindow", u"255", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"V Max:", None))
        self.btn_resetHSV.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u7f6e\u5f53\u524dHSV\u4e3a\u9ed8\u8ba4\u503c", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c\u65e5\u5fd7", None))
        self.btn_rebootVision.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542f\u7ebf\u7a0b", None))
        self.check_show1.setText(QCoreApplication.translate("MainWindow", u"show", None))
        self.check_show2.setText(QCoreApplication.translate("MainWindow", u"show", None))
        self.check_show3.setText(QCoreApplication.translate("MainWindow", u"show", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u84dd\u8272\u8865\u507f\uff1a", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"x:", None))
        self.entry_blueDeltaX.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.entry_blueDeltaY.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"y:", None))
        self.btn_saveblueDelta.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u89c6\u89c9\u754c\u9762", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"\u4efb\u52a1\u9009\u62e9\uff1a", None))
        self.cBox_subTaskNum.setItemText(0, QCoreApplication.translate("MainWindow", u"10 \u5b50\u4efb\u52a1\uff08\u539f\u6599\u533a\u7269\u6599\u6293\u53d6\uff09", None))
        self.cBox_subTaskNum.setItemText(1, QCoreApplication.translate("MainWindow", u"20 \u5b50\u4efb\u52a1\uff08\u7c97\u52a0\u5de5\u533a\u653e\u7f6e\u6293\u53d6\uff09", None))
        self.cBox_subTaskNum.setItemText(2, QCoreApplication.translate("MainWindow", u"31 \u5b50\u4efb\u52a1\uff08\u6682\u5b58\u533a\u653e\u7f6e\uff09", None))
        self.cBox_subTaskNum.setItemText(3, QCoreApplication.translate("MainWindow", u"32 \u5b50\u4efb\u52a1\uff08\u6682\u5b58\u533a\u7801\u579b\u7c97\u5b9a\u4f4d\uff09", None))
        self.cBox_subTaskNum.setItemText(4, QCoreApplication.translate("MainWindow", u"33 \u5b50\u4efb\u52a1\uff08\u6682\u5b58\u533a\u7801\u579b\u7cbe\u5b9a\u4f4d\uff09", None))

        self.cBox_colorOrder.setItemText(0, QCoreApplication.translate("MainWindow", u"123", None))
        self.cBox_colorOrder.setItemText(1, QCoreApplication.translate("MainWindow", u"132", None))
        self.cBox_colorOrder.setItemText(2, QCoreApplication.translate("MainWindow", u"213", None))
        self.cBox_colorOrder.setItemText(3, QCoreApplication.translate("MainWindow", u"231", None))
        self.cBox_colorOrder.setItemText(4, QCoreApplication.translate("MainWindow", u"312", None))
        self.cBox_colorOrder.setItemText(5, QCoreApplication.translate("MainWindow", u"321", None))

        self.label_62.setText(QCoreApplication.translate("MainWindow", u"\u989c\u8272\u987a\u5e8f\uff1a", None))
        self.btn_taskStart.setText(QCoreApplication.translate("MainWindow", u"\u4efb\u52a1\u5f00\u59cb", None))
        self.btn_cancelReached.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6240\u6709\u5173\u8282\u5230\u4f4d\u8fd4\u56de", None))
        self.btn_taskCancel.setText(QCoreApplication.translate("MainWindow", u"\u4efb\u52a1\u53d6\u6d88", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u76ee\u6807X\uff1a", None))
        self.entry_carRelX.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.entry_carRelY.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u76ee\u6807Y\uff1a", None))
        self.entry_carRelT.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c\u65f6\u95f4T\uff1a", None))
        self.btn_carRelMove.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u76f4\u7ebf\u79fb\u52a8\uff08\u76f8\u5bf9\uff09", None))
        self.entryR_isCarReached.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u5230\u4f4d\u6807\u5fd7\uff1a", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u89c6\u89c9\u5b9a\u4f4d", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c\u65e5\u5fd7", None))
        self.entry_carRotateA.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u65cb\u8f6c\u901f\u5ea6T\uff1a", None))
        self.entry_carRotateS.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u65cb\u8f6c\u76ee\u6807A\uff1a", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"(\u6b63\u503c\u4e3a\u9006\u65f6\u9488\u65cb\u8f6c)", None))
        self.btn_carRotate.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u65cb\u8f6c", None))
        self.entryR_isCarRotateReached.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u8f66\u65cb\u8f6c\u5230\u4f4d\u6807\u5fd7\uff1a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u4efb\u52a1\u754c\u9762", None))
        self.btn_readQR.setText(QCoreApplication.translate("MainWindow", u"\u8bfb\u7801", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u8f6c\u76d8\u9ad8\u5ea6:", None))
        self.entry_tableHeight.setText(QCoreApplication.translate("MainWindow", u"80.0", None))
        self.btn_saveHeight.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.label_QR_Data.setText(QCoreApplication.translate("MainWindow", u"\u521d\u59cb\u5316\u4e2d", None))
        self.btn_toStartPos.setText(QCoreApplication.translate("MainWindow", u"\u51fa\u53d1\u59ff\u6001", None))
        self.btn_toDebugPos.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u59ff\u6001", None))
        self.btn_fullScreen.setText(QCoreApplication.translate("MainWindow", u"\u5207\u6362\u5168\u5c4f", None))
        self.btn_GO.setText(QCoreApplication.translate("MainWindow", u"GO!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u6bd4\u8d5b\u663e\u793a\u754c\u9762", None))
        self.connectionLabel.setText(QCoreApplication.translate("MainWindow", u"\u72b6\u6001\uff1a\u672a\u8fde\u63a5", None))
        self.sysLabel.setText(QCoreApplication.translate("MainWindow", u"\u7cfb\u7edf\uff1a\u79bb\u7ebf", None))
    # retranslateUi

